highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://org817.github.io
author: Rocku Oh

baseurl: /
title: Rocku Oh - Curriculum Vitae
name: Rocku Oh
description: Ph.D Candidate in Finance (Ulsan National Institute of Science and Technology)
interest: Financial Engineering and Data analytics by Machine Learning and Data Mining
email: org817@gmail.com
email_full: mailto:org817@gmail.com
website: https://github.com/org817/portfolio
website_full: https://github.com/org817/portfolio
github: org817
tel: +82 10 3471 3511

g-analytics : UA-128686774-1
# needed for travis-ci build
exclude: [vendor]
